### ISSUE TITLE
BE: Character Creation 

### ISSUE THREAD

**Issue by Lion-alt** [keykey7/fabbwled#14]
**Is your feature request related to a problem? At the beginning a character should be created*
A clear and concise description of what the problem is.
Ex. a missing requirement for section 1 is '...'.
```text
A character is created with the type and everything else defined
```

**Describe the solution you'd like**
- The backend should handle the input (profession of user) (beginning stamina of user) and save it inside the a CharacterDto which is then asigned inside PlayerDto
-  profession, stamina, description, posessions, stats per character saved, name
- Test the CharacterService and the return value of defence from PlayerDto @adrsch04 

**API description**
GET /api/player/characters/all -> Get all characters
POST /api/player/getCharacter-> Get character from current player
POST /api/player/setCharacter -> Argument a PlayerDto

**Additional context**

**Comment by keykey7** [comment]
(minor) each book has its own set of starting characters. you might want to include the bookId in the `GET` call.

**Comment by Lion-alt** [comment]
@adrsch04 Write tests for this code
