### ISSUE TITLE
Shard currency system

### ISSUE THREAD

**Issue by lucasmillanm** [keykey7/fabbwled#215]
**Is your feature request related to a problem? Please describe.**
#209 
```
Be able to gain shards or lose shards
```

**Describe the solution you'd like**
- Character has shards
- Depending on the section add or subtract the given amount of shards

**Comment by keykey7** [comment]
Additionally enforce the game rules: shards can never become negative.

**Comment by Nilstrieb** [comment]
duplicate of #10
