### ISSUE TITLE
ABILITY roll

### ISSUE THREAD

**Issue by Noeell** [keykey7/fabbwled#229]
# Description
Example: `make a MAGIC roll with difficulty 13`

> USING ABILITIES
Fighting is often not the easiest or safest way to tackle a
situation. When you get a chance to use one of your other
abilities, you will be told the Difficulty of the task. You roll two
dice and add your score in the ability, and to succeed in the task
you must get higher than the Difficulty.
Example:
You are at the bottom of a cliff. You can use THIEVERY to climb it, and
the climb is Difficulty 9. Suppose your THIEVERY score is 4. This
means you must roll at least 6 on the dice to make the climb.

# Tasks
## Tasks backend
TODO

## Tasks frontend
TODO

**Comment by Nilstrieb** [comment]
@kimberlymo you're dealing with rolls already, this is yours now

**Comment by Nilstrieb** [comment]
Important: we only want to handle simple cases like "CHARISMA difficulty 11"

**Comment by Noeell** [comment]
is implemented now
