### ISSUE TITLE
BE: Add some sort of API specification

### ISSUE THREAD

**Issue by corsin-lehre** [keykey7/fabbwled#23]
**Is your feature request related to a problem? Please describe.**
We need a way to quickly see which endpoints are accessible and how to access them

**Describe the solution you'd like**
- OpenAPI Specification would be perfect

**Describe alternatives you've considered**
We could just read the source code, but this takes alot of time

**Additional context**
[Swagger](https://swagger.io/specification/)

**Comment by Nilstrieb** [comment]
OpenAPI makes sense.

**Comment by corsin-lehre** [comment]
danke

**Comment by keykey7** [comment]
I suggest https://springdoc.org/ and keeping the backend code-first (but generating oas definition and providing a swagger endpoint).

**Comment by Rwael** [comment]
Done with https://github.com/keykey7/fabbwled/pull/439
