### ISSUE TITLE
Resurrection Deal

### ISSUE THREAD

**Issue by Rwael** [keykey7/fabbwled#279]
**Is your feature request related to a problem? Please describe.**
If you have a resurrection deal you can escape death once and go on.
```text
Your adventures end here – unless you have a
resurrection deal. - after a fight or event
```

**Describe the solution you'd like**
- Check if there is a Resurrection Deal item in the inventory?

**Describe alternatives you've considered**
Or is it a state on the player? Several Resurrection Deals in inventory?

**Comment by keykey7** [comment]
Note: resurrection deals is a "general concept". There can only ever be 1 resurrection-deal active at once.
Each resurrection deal has a unique name (depending on the god who issued it) and therefore a unique section to continue reading once it triggered. Like
```
record ResurrectionDeal(String name, SectionId target);

record PlayerDto( ...
   ResurrectionDeal resurrectionDeal, ...
){ ... }
```
