### ISSUE TITLE
Thievery Roll

### ISSUE THREAD

**Issue by Rwael** [keykey7/fabbwled#298]
**Is your feature request related to a problem? Please describe.**
Implement Thievery roll like Ability Roll
#229 
#237 

#293
```text
Make a THIEVERY
roll at Difficulty 11.
```

**Describe the solution you'd like**
- A clear and concise description of what you want to happen. Differentiate in backend and frontend behaviour.
- If applicable suggest an API change and include a sample request snipped.
Ex. `{"skillcheck":{...,"modifier":"3dice"}...`

**Describe alternatives you've considered**

**Additional context**

**Comment by keykey7** [comment]
duplicate of https://github.com/keykey7/fabbwled/issues/229

as all ability rolls behave the same. (but the description of this issue is way better than the #229 one atm :) )

**Comment by keykey7** [comment]
Duplicate of #229
