### ISSUE TITLE
Add and condition for ifs

### ISSUE THREAD

**Issue by corsin-lehre** [keykey7/fabbwled#499]
needed for example in `If you have the codeword Ambuscade, turn to 375. If not, but you have the codeword Ark and the royal ring, turn to 255.`

**Comment by Nilstrieb** [comment]
Could look something like
```yaml
and:
  - CONDITION1
  - CONDITION2
```

**Comment by keykey7** [comment]
...might also be treated as a "non simple case". and thus not available via yaml... it's kinda easy to be implemented in java however.

**Comment by Nilstrieb** [comment]
its very to implement in the YAML so why not

**Comment by stevan04** [comment]
added the "and" and "or" condition to the section-schema.json, currently implementing in java code.

goal is to use both conditions as arrays for the case that they needed multiple times like this:
`if:
  hasKeyword: "example"
  and:
    - case1
    - case2
    - case3`

**Comment by stevan04** [comment]
will not be implemented, also isn't necessary.
