### ISSUE TITLE
Add ability to remove item from inventory

### ISSUE THREAD

**Issue by corsin-lehre** [keykey7/fabbwled#500]
For example:
`f  you  have  a  blessing  of  Safety  from Storms it is now gone – delete it from your blessings box. There are no other effects.`

**Comment by keykey7** [comment]
this is a blessing (not an item). all blessings are activatable after a failed ability-roll. they are automatically gone afterwards. (the ticket is good but doesn't really match the example :) )

**Comment by Nilstrieb** [comment]
duplicate of #228
